In [1]:
import altair as alt
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
visus_folder_name = 'visualizations'
os.makedirs(visus_folder_name, exist_ok=True)
visus_path = os.path.join(os.getcwd(), visus_folder_name)

In [3]:
df = pd.read_json('./evaluation/aggregate_metrics.json')

In [4]:
df_punchlines = pd.DataFrame(df.loc["punchlines"].tolist(), index=df.columns)
df_punchlines

,dice_similarity,jaccard_similarity,levenshtein_distance,hit_rate_pre_treatment,hit_rate
gemma-3-gaia-pt-br-4b-it,0.483833,0.357420,28.490526,0.000000,0.993684
mixtral-8x7b-instruct-v01,0.543614,0.412302,25.267368,0.989474,0.989474
granite-3-3-8b-instruct,0.528261,0.399735,31.288421,0.842105,0.945263
gemini-2.5-flash,0.677834,0.560615,19.029474,0.993684,0.993684
gpt-4,0.728631,0.606435,24.040000,0.997895,0.997895
llama-3-405b-instruct,0.590931,0.469324,24.128421,0.983158,0.993684

In [5]:
df_dice = df_punchlines[['dice_similarity']].reset_index().rename(columns={'index': 'model'})
df_lev = df_punchlines[['levenshtein_distance']].reset_index().rename(columns={'index': 'model'})

dice_order = df_dice.sort_values('dice_similarity')['model'].tolist()[::-1]
lev_order = df_lev.sort_values('levenshtein_distance')['model'].tolist()[::1]

chart_dice = alt.layer(
    alt.Chart(df_dice).mark_bar(size=80).encode(
        x=alt.X('model:N', sort=dice_order, title=' ',
                scale=alt.Scale(paddingInner=0.1), axis=alt.Axis(grid=False)),
        y=alt.Y('dice_similarity:Q', title='Média da Similaridade de Dice', axis=alt.Axis(grid=False)),
        color=alt.Color('model:N', legend=None)
    ),
    alt.Chart(df_dice).mark_text(
        align='center',
        baseline='bottom',
        dy=-2
    ).encode(
        x=alt.X('model:N', sort=dice_order),
        y='dice_similarity:Q',
        text=alt.Text('dice_similarity:Q', format=".2f")
    )
).properties(
    width=700,
    height=300,
    title='Sobreposição de Punchlines por Modelo (Similaridade de Dice)'
).configure_axisX(
    labelAngle=0,
    labelAlign='center'
)

chart_lev = alt.layer(
    alt.Chart(df_lev).mark_bar(size=80).encode(
        x=alt.X('model:N', sort=lev_order, title=' ',
                scale=alt.Scale(paddingInner=0.1), axis=alt.Axis(grid=False)),
        y=alt.Y('levenshtein_distance:Q', title='Média da Distância de Levenshtein', axis=alt.Axis(grid=False)),
        color=alt.Color('model:N', legend=None)
    ),
    alt.Chart(df_lev).mark_text(
        align='center',
        baseline='bottom',
        dy=-2
    ).encode(
        x=alt.X('model:N', sort=lev_order),
        y='levenshtein_distance:Q',
        text=alt.Text('levenshtein_distance:Q', format=".2f")
    )
).properties(
    width=700,
    height=300,
    title='Distância de Punchlines por Modelo (Distância de Levenshtein)'
).configure_axisX(
    labelAngle=0,
    labelAlign='center'
)

chart_dice.save(os.path.join(visus_path,"punchlines_dice.png"), scale_factor=3.0)
chart_lev.save(os.path.join(visus_path, "punchlines_levenshtein.png"), scale_factor=3.0)

chart_dice.show()
chart_lev.show()

alt.LayerChart(...)

alt.LayerChart(...)

In [6]:
df_texts_explanations = df.loc["texts_explanations"].to_frame().T
df_texts_explanations

,gemma-3-gaia-pt-br-4b-it,mixtral-8x7b-instruct-v01,granite-3-3-8b-instruct,gemini-2.5-flash,gpt-4,llama-3-405b-instruct
texts_explanations,4.629474,3.364211,3.642105,4.635789,4.282105,3.972632

In [7]:
texts_expl = df.loc["texts_explanations"].astype(float)
texts_df = texts_expl.reset_index()
texts_df.columns = ["Modelo", "Concordância Média"]

chart = alt.layer(
    alt.Chart(texts_df).mark_bar(size=80).encode(
        y=alt.Y('Concordância Média:Q',
                title='Nível médio de concordância (Modelo Juiz)',
                scale=alt.Scale(domain=[0, texts_df["Concordância Média"].max() + 0.5]),
                axis=alt.Axis(grid=False)),
        x=alt.X('Modelo:N',
                sort='-y',
                title='',
                axis=alt.Axis(grid=False, labelAngle=0)),
        color=alt.Color('Modelo:N', legend=None),
        tooltip=["Modelo", "Concordância Média"]
    ),
    alt.Chart(texts_df).mark_text(
        align='center',
        baseline='bottom',
        dy=-3
    ).encode(
        x=alt.X('Modelo:N', sort='-y'),
        y='Concordância Média:Q',
        text=alt.Text('Concordância Média:Q', format='.2f')
    )
).properties(
    width=600,
    height=400,
    title="Avaliação das Explicações dos Textos Humorísticos por Modelo"
)
chart.save(os.path.join(visus_path, "explicacoes_concordancia.png"), scale_factor=3.0)
chart

alt.LayerChart(...)

In [8]:
df.loc["comic_styles"]

gemma-3-gaia-pt-br-4b-it     {'f1_score': {'fun': 0.867699642431466, 'humor...
mixtral-8x7b-instruct-v01    {'f1_score': {'fun': 0.8688327316486161, 'humo...
granite-3-3-8b-instruct      {'f1_score': {'fun': 0.0, 'humor': 0.222222222...
gemini-2.5-flash             {'f1_score': {'fun': 0.7873563218390801, 'humo...
gpt-4                        {'f1_score': {'fun': 0.851511169513797, 'humor...
llama-3-405b-instruct        {'f1_score': {'fun': 0.838874680306905, 'humor...
Name: comic_styles, dtype: object

In [9]:
df_comic_styles = pd.DataFrame(df.loc["comic_styles"].dropna().tolist(), index=df.columns[df.loc["comic_styles"].notna()])
df_comic_styles

,f1_score,precision,recall,accuracy,f1_macro,f1_micro,hit_rate_pre_treatment,hit_rate,omission_rate
gemma-3-gaia-pt-br-4b-it,"{'fun': 0.867699642431466, 'humor': 0.84987893...","{'fun': 0.7663157894736841, 'humor': 0.7389473...","{'fun': 1.0, 'humor': 1.0, 'nonsense': 1.0, 'w...","{'fun': 0.7663157894736841, 'humor': 0.7389473...",0.125000,0.667135,0.0,1.000000,0.000000
mixtral-8x7b-instruct-v01,"{'fun': 0.8688327316486161, 'humor': 0.8511685...","{'fun': 0.7680851063829781, 'humor': 0.7408993...","{'fun': 1.0, 'humor': 1.0, 'nonsense': 1.0, 'w...","{'fun': 0.7680851063829781, 'humor': 0.7408993...",0.139617,0.692837,0.0,0.982895,0.017105
granite-3-3-8b-instruct,"{'fun': 0.0, 'humor': 0.22222222222222202, 'no...","{'fun': 0.0, 'humor': 0.833333333333333, 'nons...","{'fun': 0.0, 'humor': 0.128205128205128, 'nons...","{'fun': 0.23368421052631502, 'humor': 0.336842...",0.184258,0.791349,0.0,1.000000,0.000000
gemini-2.5-flash,"{'fun': 0.7873563218390801, 'humor': 0.5658914...","{'fun': 0.825301204819277, 'humor': 0.88484848...","{'fun': 0.7527472527472521, 'humor': 0.4159544...","{'fun': 0.688421052631578, 'humor': 0.52842105...",0.249473,0.997890,1.0,1.000000,0.000000
gpt-4,"{'fun': 0.851511169513797, 'humor': 0.55619047...","{'fun': 0.816120906801007, 'humor': 0.83908045...","{'fun': 0.8901098901098901, 'humor': 0.4159544...","{'fun': 0.7621052631578941, 'humor': 0.5094736...",0.248408,0.993644,1.0,1.000000,0.000000
llama-3-405b-instruct,"{'fun': 0.838874680306905, 'humor': 0.73851030...","{'fun': 0.7846889952153111, 'humor': 0.8321428...","{'fun': 0.9010989010989011, 'humor': 0.6638176...","{'fun': 0.734736842105263, 'humor': 0.65263157...",0.242541,0.970748,0.0,1.000000,0.000000

In [10]:
def graph_all_models_per_style(model_names):
    data = []

    for model_name in model_names:
        f1_scores = df_comic_styles.loc[model_name]['f1_score']
        for style, score in f1_scores.items():
            data.append({
                'style': style,
                'model': model_name,
                'score': score
            })

    df_all = pd.DataFrame(data)

    chart = alt.Chart(df_all).mark_bar().encode(
        x=alt.X('style:N', title=None, axis=alt.Axis(labelAngle=0)),
        y=alt.Y('score:Q', title='F1-Score'),
        color=alt.Color('model:N', title='Modelo'),
        xOffset=alt.X('model:N')  # <-- barras lado a lado dentro do mesmo estilo
    ).properties(
        width=500,
        height=400,
        title='F1-Score por Estilo Cômico e Modelo'
    )

    chart.save(os.path.join(visus_path, "f1_per_style_all_models.png"), scale_factor=3.0)
    chart.show()

model_names = df_comic_styles.index
graph_all_models_per_style(model_names)

alt.Chart(...)